# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: trusty
cache: packages
after_success:
  - Rscript -e 'covr::codecov()'
r_github_packages: ropensci/ckanr
addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
r:
  - oldrel
  - release
  - devel
